### ISSUE TITLE
Any pre-trained models?

### ISSUE THREAD

**Issue by SaadBazaz** [chaoyivision/SGGpoint#1]
Hey there, 
I can't find any pretrained models which could be used to test the output of this Architecture. Any hints?

**Comment by chaoyivision** [comment]
Hey,

Thanks for your interests! The model weights are not provided. Some reproduction instructions are now summarised under your colleague's [post](https://github.com/chaoyivision/SGGpoint/issues/2) - pls have a look and hope it helps :). 

Pls also be noted that for the graph representation learning, multiple runs were conducted and we then reported an averaged score among them (full details can be found in our [supp.](https://sggpoint.github.io/supplementary.pdf)).
