### ISSUE TITLE
How do i train the model?

### ISSUE THREAD

**Issue by zohairhadi** [chaoyivision/SGGpoint#2]
Hello,

I can't really find instructions on training the model mentioned in the paper. Any help would be hugely appreciated.

**Comment by chaoyivision** [comment]
Hi,

Thanks for your interests! Unfortunately, we may not have a full code releasing plan currently, and here is some instructions on deriving/reproducing our results on:

1) Any customised 3D Point-based Scene Graph datasets. You may simply replace yours with our [EdgeGCN](https://github.com/chaoyivision/SGGpoint/blob/main/EdgeGCN.py) to derive a comparing result, with other training settings maintained.

2) 3DSSG. Please use our cleaned [3DSSG-O27R16 dataset](https://sggpoint.github.io/#dataset) and some [guidances](https://chaoyivision.github.io/SGGpoint/#last-few-steps) are provided for building dataloader.py. The implementations of 
 the backbone networks (PointNet + DGCNN) that we borrowed from [Yue Wang et al](https://github.com/WangYueFt/dgcnn) can be found [here](https://github.com/chaoyivision/SGGpoint/blob/main/SubNetworks.py).

3) Graph datasets (Cora/CiteSeer/Pubmed/Tox21/BBBP). With other details specified in [supp.](https://sggpoint.github.io/supplementary.pdf), the training scripts that we used in our studies could be found [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#learning-methods-on-graphs) (for PyG on node-wise classification) and [here](https://github.com/awslabs/dgl-lifesci/blob/master/examples/property_prediction/moleculenet/classification.py) (for DGL on whole-graph recognition). You could then replace their demo networks with our EdgeGCN for reproduction.
